name: ride_hailing
version: "1.0.0"
config-version: 2
profile: ride_hailing

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: "2026-01-01"
  bq_location: "us"

seeds:
  ride_hailing:
    indonesia_public_holidays:
      +column_types:
        holiday_date: date
        holiday_name: string
      +tags: ["daily"]

models:
  ride_hailing:
    staging:
      +materialized: view
      cdc:
        +tags: ["hourly"]
      pg:
        +tags: ["daily"]
    intermediate:
      +materialized: view
      +tags: ["daily"]
      int__ride_enriched:
        +materialized: incremental
        +tags: ["hourly"]
      int__payment_enriched:
        +materialized: incremental
        +tags: ["hourly"]
      int__ride_status_transitions:
        +materialized: incremental
        +tags: ["daily"]
      int__payment_audit_trail:
        +materialized: incremental
        +tags: ["hourly"]
      int__rider_lifetime:
        +materialized: table
        +tags: ["daily"]
    marts:
      +materialized: table
      dims:
        +tags: ["daily"]
      facts:
        fct_rides:
          +materialized: incremental
          +tags: ["hourly"]
          +partition_by:
            field: ride_date
            data_type: date
          +cluster_by: ["city_code", "service_type", "ride_status"]
        fct_payments:
          +materialized: incremental
          +tags: ["hourly"]
          +partition_by:
            field: txn_date
            data_type: date
          +cluster_by: ["payment_status", "provider_name"]
        fct_reviews:
          +tags: ["daily"]
          +partition_by:
            field: review_date
            data_type: date
          +cluster_by: ["review_type"]
        fct_ride_status_transitions:
          +materialized: incremental
          +tags: ["daily"]
          +partition_by:
            field: changed_date
            data_type: date
          +cluster_by: ["new_status"]
      aggregates:
        +tags: ["daily"]
