select
    cast(payment_transaction_id as int64) as payment_transaction_id,
    cast(ride_id as int64) as ride_id,
    cast(rider_id as int64) as rider_id,
    cast(payment_method_id as int64) as payment_method_id,
    lower(cast(provider_name as string)) as provider_name,
    cast(provider_transaction_id as string) as provider_transaction_id,
    cast(idempotency_key as string) as idempotency_key,
    cast(amount as numeric) as amount,
    cast(method_fee as numeric) as method_fee,
    upper(cast(currency_code as string)) as currency_code,
    upper(cast(payment_status as string)) as payment_status,
    upper(cast(failure_code as string)) as failure_code,
    cast(failure_message as string) as failure_message,
    cast(authorized_at as timestamp) as authorized_at,
    cast(captured_at as timestamp) as captured_at,
    cast(paid_at as timestamp) as paid_at,
    cast(created_at as timestamp) as created_at,
    cast(updated_at as timestamp) as updated_at,
    cast(deleted_at as timestamp) as deleted_at,
    deleted_at is not null as is_deleted
from {{ source('bronze_mysql', 'payment_transaction') }}
