select
    cast(ride_id as int64) as ride_id,
    cast(rider_id as int64) as rider_id,
    cast(driver_id as int64) as driver_id,
    cast(vehicle_id as int64) as vehicle_id,
    upper(cast(ride_status as string)) as ride_status,
    upper(cast(service_type as string)) as service_type,
    upper(cast(city_code as string)) as city_code,
    cast(requested_at as timestamp) as requested_at,
    cast(accepted_at as timestamp) as accepted_at,
    cast(arrived_at as timestamp) as arrived_at,
    cast(started_at as timestamp) as started_at,
    cast(completed_at as timestamp) as completed_at,
    cast(cancelled_at as timestamp) as cancelled_at,
    upper(cast(cancelled_by_type as string)) as cancelled_by_type,
    upper(cast(cancel_reason_code as string)) as cancel_reason_code,
    cast(estimated_distance_km as numeric) as estimated_distance_km,
    cast(estimated_duration_min as numeric) as estimated_duration_min,
    cast(created_at as timestamp) as created_at,
    cast(updated_at as timestamp) as updated_at,
    cast(deleted_at as timestamp) as deleted_at,
    date(cast(requested_at as timestamp), 'Asia/Jakarta') as requested_date,
    extract(hour from cast(requested_at as timestamp) at time zone 'Asia/Jakarta') as requested_hour,
    extract(dayofweek from date(cast(requested_at as timestamp), 'Asia/Jakarta')) in (1, 7) as is_weekend,
    extract(hour from cast(requested_at as timestamp) at time zone 'Asia/Jakarta') between 7 and 9
      or extract(hour from cast(requested_at as timestamp) at time zone 'Asia/Jakarta') between 17 and 20 as is_peak_hour,
    ride_status = 'COMPLETED' as is_completed,
    ride_status = 'CANCELLED' as is_cancelled,
    ride_status = 'PAYMENT_FAILED' as is_payment_failed,
    deleted_at is not null as is_deleted
from {{ source('bronze_pg', 'ride') }}
