select
    cast(ride_id as int64) as ride_id,
    cast(rider_id as int64) as rider_id,
    cast(driver_id as int64) as driver_id,
    cast(vehicle_id as int64) as vehicle_id,
    upper(ride_status) as ride_status,
    upper(service_type) as service_type,
    upper(city_code) as city_code,
    {{ safe_parse_cdc_timestamp('requested_at') }} as requested_at,
    {{ safe_parse_cdc_timestamp('accepted_at') }} as accepted_at,
    {{ safe_parse_cdc_timestamp('arrived_at') }} as arrived_at,
    {{ safe_parse_cdc_timestamp('started_at') }} as started_at,
    {{ safe_parse_cdc_timestamp('completed_at') }} as completed_at,
    {{ safe_parse_cdc_timestamp('cancelled_at') }} as cancelled_at,
    cast(cancelled_by_user_id as int64) as cancelled_by_user_id,
    upper(cancel_reason_code) as cancel_reason_code,
    cancel_reason_note,
    cast(estimated_distance_km as numeric) as estimated_distance_km,
    cast(estimated_duration_min as numeric) as estimated_duration_min,
    {{ safe_parse_cdc_timestamp('created_at') }} as created_at,
    {{ safe_parse_cdc_timestamp('updated_at') }} as updated_at,
    lower(__op) as cdc_operation,
    __table as cdc_table,
    cast(__lsn as int64) as cdc_lsn,
    timestamp_millis(cast(__source_ts_ms as int64)) as cdc_event_at,
    _partitiontime as cdc_partition_at,
    {{ audit_columns() }}
from {{ source('bronze_cdc_events', 'ride_events') }}
where _partitiontime >= timestamp_sub(current_timestamp(), interval {{ var('cdc_lookback_hours', 720) }} hour)
