connector.name=mysql
# if use network_mode: host, use port 3307
connection-url=jdbc:mysql://mysql-billing:3306/${ENV:MYSQL_DATABASE}
connection-user=${ENV:MYSQL_USER}
connection-password=${ENV:MYSQL_PASSWORD}

