connector.name=postgresql
# if use network_mode: host, use port 5433
connection-url=jdbc:postgresql://postgres-ops:5432/${ENV:POSTGRES_DB}
connection-user=${ENV:POSTGRES_USER}
connection-password=${ENV:POSTGRES_PASSWORD}


